### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by arthurvr** [mamal72/ama#2]

**Comment by mamal72** [comment]
Hm.. Such a hard question!
There are tons of awesome projects on Github. So I choose [awesome](https://github.com/sindresorhus/awesome) project cause it's a project which shows us more awesome things.
awesome-nodejs, awesome-sysadmins, awesome-php and a lot more awesome all are great.
Another project that I really love is [The Art of Command Line](https://github.com/jlevy/the-art-of-command-line) which is really really awesome! I can't think of better projects than these ones. :+1:
